export const ADD_TO_WATCH_LIST = 'ADD_TO_WATCH_LIST';
export const DELETE_FROM_WATCH_LIST = 'DELETE_FROM_WATCH_LIST';
export const SWITCH_WATCHING = 'SWITCH_WATCHING';
export const UPDATE_DATA = 'UPDATE_DATA';
